name: Build and Release Linux Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'
        
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flask requests

      - name: Build binary with PyInstaller
        run: |
          pyinstaller seadex-torznab.py --onefile --name seadex-torznab
          mkdir -p release
          cp dist/seadex-torznab release/
          cd release
          zip seadex-torznab-linux-binary.zip seadex-torznab

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/seadex-torznab-linux-binary.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
